# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사이트명'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(unique=True, verbose_name='도메인'),
        ),
    ]
